import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import clsx from "clsx";

export const metadata: Metadata = {
    title: "EVROOMA",
    icons: [
        {
            rel: "icon",
            url: "/light.svg",
            media: "(prefers-color-scheme: light)",
        },
        {
            rel: "icon",
            url: "/dark.svg",
            media: "(prefers-color-scheme: dark)",
        },
    ],
    description: "Generated by create next app",
};

const inter = Inter({ subsets: ["latin"] });

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body className={clsx(inter.className, "antialiased")}>
                {children}
            </body>
        </html>
    );
}
